M48
; DRILL file {KiCad (6.0.11)} date Wed Mar  8 11:42:26 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-03-08T11:42:26-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.11)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0630
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1378
%
G90
G05
T1
X7.3131Y-3.72
X7.51Y-3.5231
X7.51Y-3.9169
T2
X4.6942Y-3.28
T0
M30
