M48
; DRILL file {KiCad (6.0.11)} date Fri Mar  3 21:19:15 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-03-03T21:19:15-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.11)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0630
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1378
%
G90
G05
T1
X7.2925Y-4.565
X7.4894Y-4.3681
X7.4894Y-4.7619
T2
X4.6942Y-3.28
T0
M30
